[package]
name = "spaghetti"
version = "0.1.0"
authors = ["Jack Waudby <j.waudby2@newcastle.ac.uk>"]
edition = "2018"
readme = "README.md"
description = """
A concurrency control evaluation framework.
"""

[[bin]]
name = "spag-client"
path = "src/bin/client.rs"

[[bin]]
name = "spag-server"
path = "src/bin/server.rs"

[dependencies]
chashmap = "2.2.2"
rand = "0.8.0"
rust-ini = "0.16.0"
lazy_static = "1.4.0"
log="0.4"
env_logger="0.7"
config = "0.10"
bytes = "1"
serde = {version = "1.0.118", features = ["derive"]}
bincode = "1.3.1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.5"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
clap = "3.0.0-beta.2"