address = "10.0.0.6"
port = 6142
log = "info"

mpsc_size = 32

generator_mode = "flood"
think_time = 1000

workload = "tatp"
transactions = 1000000

subscribers = 100000

warehouses = 5
districts = 10
customers = 100
max_items = 100
