address = "10.0.0.6"
port = 6142
log = "info"

mpsc_size = 32

generator_mode = "closed"
think_time = 0

workload = "tatp"
transactions = 1001000

subscribers = 10000

warehouses = 5
districts = 10
customers = 100
max_items = 100
