address = "127.0.0.1"
port = 6142
log = "info"

mpsc_size = 32

generator_mode = "flood"
think_time = 1000

workload = "tatp"
transactions = 10

subscribers = 1

warehouses = 5
districts = 10
customers = 100
max_items = 100
