address = "10.0.0.6"
port = 6142
log = "info"

mpsc_size = 32

generator_mode = "closed"
think_time = 0

workload = "tatp"
transactions = 100000

subscribers = 100000

warehouses = 5
districts = 10
customers = 100
max_items = 100

set_seed = true
accounts = 18000
hotspot_use_fixed_size = false
hotspot_percentage = 25
hotspot_fixed_size = 100
min_balance = 10000.0
max_balance = 50000.0
send_payment_amount = 5.0
deposit_checking_amount = 1.3
transact_savings_amount = 20.20
write_check_amount = 5.0