log = "info"

transactions = 1000
warmup = 1
set_seed = false

protocol="sgt"
workers = 6
hit_gc = 5000

scale_factor = 1
workload = "smallbank"
schema = "smallbank_schema.txt"
load = true

use_nurand = true

use_balance_mix = false
hotspot_use_fixed_size = true
