log = "info"

transactions = 1000
warmup = 1

protocol="2pl"
workers = 6
hit_gc = 5000

scale_factor = 1
workload = "tatp"
schema = "tatp_schema.txt"
load = true

use_nurand = true

balance_mix = false
hotspot_use_fixed_size = true
