log = "info"

transactions = 100
timeout = 10
warmup = 1
set_seed = false

protocol="sgt"
workers = 6
garbage_collection = true
garbage_collection_sleep = 1

scale_factor = 1
workload = "smallbank"
anomaly = "g1c"
load = false

nurand = true

use_balance_mix = false
hotspot_use_fixed_size = true
