log = "info"

transactions = 10000000
timeout = 1
warmup = 10
set_seed = false

protocol="opt-hit"
workers = 6
hit_gc = 5000

scale_factor = 1
workload = "tatp"
schema = "tatp_schema.txt"
load = true

nurand = true

use_balance_mix = false
hotspot_use_fixed_size = true
