log = "info"

transactions = 10000
timeout = 10
warmup = 100
set_seed = false

protocol="opt-hit"
workers = 6
garbage_collection = true
garbage_collection_sleep = 10

scale_factor = 1
workload = "tatp"
schema = "tatp_schema.txt"
load = true

nurand = true

use_balance_mix = false
hotspot_use_fixed_size = true
