log = "info"
workload = "smallbank"
transactions = 10
seed = 42
subscribers = 10

warehouses = 5
districts = 10
customers = 100
max_items = 100

set_seed = true
balance_mix = false
accounts = 10
hotspot_use_fixed_size = false
hotspot_percentage = 0.25
hotspot_fixed_size = 100
min_balance = 10000
max_balance = 50000
send_payment_amount = 5.0
deposit_checking_amount = 1.3
transact_savings_amount = 20.20
write_check_amount = 5.0