log = "info"
workload = "tatp"
transactions = 10
seed = 42
set_seed = false

params = false
scale_factor = 1

use_nurand = true

warehouses = 5
districts = 10
customers = 100
max_items = 100

balance_mix = false
accounts = 10
hotspot_use_fixed_size = false
hotspot_percentage = 0.25
hotspot_fixed_size = 100
min_balance = 10000
max_balance = 50000
send_payment_amount = 5.0
deposit_checking_amount = 1.3
transact_savings_amount = 20.20
write_check_amount = 5.0