log = "info"
log_results = false
transactions = 10000
set_seed = false
protocol="sgt"
cores = 1
scale_factor = 1
workload = "smallbank"
warmup = 30
execution = 120

# MSGT
dfs = "reduced"

# TATP
nurand = true

# SmallBank
use_balance_mix = false
isolation_mix = "high"

# YCSB
theta = 0.5
update_rate = 0.5
serializable_rate = 0.5
queries = 10


