log = "info"
record = true
log_results = false

transactions = 10000

timeout = 1
set_seed = false

protocol="sgt"
cores = 1
relevant_cycle_check = true
garbage_collection = false
garbage_collection_sleep = 1

scale_factor = 1

workload = "smallbank"
anomaly = "g1c"
load = false

nurand = true
use_balance_mix = false
