address = "127.0.0.1"
port = 6142
log = "info"
timeout = 5
mpsc_size = 32

warmup = 2

protocol="2pl"
workers = 4

transactions = 10
workload = "tatp"
subscribers = 1

warehouses = 5
districts = 10
customers = 100
max_items = 100
