log = "info"
record = true
log_results = false

transactions = 10000
timeout = 1
set_seed = false

protocol="sgt"
cores = 1
dfs = "reduced"
garbage_collection = false
garbage_collection_sleep = 1

scale_factor = 1

workload = "smallbank"
anomaly = "g1c"
load = false

nurand = true

use_balance_mix = false
isolation_mix = "mid"

theta = 0.5
update_rate = 0.5
serializable_rate = 0.5

increase = 1
decrease = 2
watermark = 100
no_wait_write = false

type_aware = false