address = "127.0.0.1"
port = 6142
log = "debug"
timeout = 5
mpsc_size = 32
load = false
clients = 4

protocol="2pl"
workers = 4

warmup = 1
generator_mode = "closed"
think_time = 1000

transactions = 10
workload = "smallbank"

schema = "smallbank_schema.txt"

set_seed = true
seed = 1
balance_mix = false
accounts = 10
hotspot_use_fixed_size = false
hotspot_percentage = 0.25
hotspot_fixed_size = 100
min_balance = 10000
max_balance = 50000
send_payment_amount = 5.0
deposit_checking_amount = 1.3
transact_savings_amount = 20.20
write_check_amount = 5.0
