address = "127.0.0.1"
port = 6142
timeout = 5
clients = 4
mpsc_size = 32
load = false
set_seed = false
seed = 42
protocol="sgt"
warmup = 1
generator_mode = "closed"
think_time = 0
transactions = 10
scale_factor = 0
workload = "tatp"
nurand = false