address = "127.0.0.1"
port = 6142
log = "debug"
timeout = 5
mpsc_size = 32
load = false

protocol="sgt"

warmup = 1
gen_delay = 1000

transactions = 3
workload = "tatp"
schema = "tatp_schema.txt"
subscribers = 3
seed = 42

clients = 1