address = "127.0.0.1"
port = 6142
log = "info"
timeout = 5
mpsc_size = 32

protocol="hit"

warmup = 2

transactions = 5
workload = "tatp"
workers = 1
schema = "tatp_schema.txt"
subscribers = 3
seed = 42

clients = 4